version: '3'
services:
  #postgres
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:     # changed from server for nginx reservered "Server"

    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules       # just leave this folder as is
      - ./server:/app          #look at server directory, and copy everything into the App directory
                                # any time app tries to access anything in app, its going to get redirected back to the server directory, and it should be automatically
                                # redirect
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379     #look on docker hub for this info
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app